### ISSUE TITLE
Main @include rule is wrong

### ISSUE THREAD

**Issue by openjck** [Watball/chat-macros#2]
The main `@include` that the script produces is `http://tagpro-*.koalabeast.com:*`, which no longer matches the production URL, `https://tagpro.koalabeast.com`.

An `@include` value of `/^https?://tagpro\.koalabeast\.com/` does work. I don't use any other servers, so I haven't tested them, but they may also need to be updated.

**Comment by Watball** [comment]
Huh, didn't know anyone still used this. Don't play anymore but I think this should've fixed it.

**Comment by openjck** [comment]
Thanks! I don't know how many people use it, but I still occasionally see people who have macros. I assume they're using your service.
